# Generated by Django 6.0.2 on 2026-03-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('requirements', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dj_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
