# Generated by Django 6.0.2 on 2026-03-23 11:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_audio',
            field=models.FileField(blank=True, null=True, upload_to=users.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_upload_path),
        ),
    ]
