# Generated by Django 4.2.11 on 2026-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_is_djteacher_profile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_djteacher',
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
