# Generated by Django 4.2.11 on 2026-04-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_is_djteacher_and_more'),
        ('users', '0005_rolechangerequest_explanation'),
    ]

    operations = [
    ]
