# Generated by Django 4.2.11 on 2026-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_bio_alter_rolechangerequest_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_djteacher',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
