# Generated by Django 6.0.2 on 2026-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_djteacher',
        ),
    ]
