# Generated by Django 6.0.2 on 2026-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_is_djteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher (DJ)'), ('producer', 'Teacher (Producer)'), ('admin_user', 'User Administrator')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='requested_role',
            field=models.CharField(choices=[('teacher', 'Teacher (DJ)'), ('producer', 'Teacher (Producer)')], default='teacher', max_length=20),
        ),
    ]
