# Generated by Django 6.0.2 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
