# Generated by Django 6.0.2 on 2026-03-29 12:58

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_lesson_fields(apps, schema_editor):
    Lesson = apps.get_model('lessonscheduler', 'Lesson')

    # Copy legacy teacher into new dj field and ensure end_time is populated.
    for lesson in Lesson.objects.all().iterator():
        if getattr(lesson, 'dj_id', None) is None and getattr(lesson, 'teacher_id', None):
            lesson.dj_id = lesson.teacher_id

        if lesson.end_time is None and lesson.start_time is not None:
            lesson.end_time = lesson.start_time + timedelta(hours=1)

        lesson.save(update_fields=['dj', 'end_time'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0002_lesson_start_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='experience_requirements',
            field=models.TextField(default='No specific requirements', help_text="e.g., 'Beginner', 'Intermediate', or specific skills needed"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.CharField(default='TBD', max_length=300),
        ),
        migrations.RunPython(backfill_lesson_fields, noop_reverse),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start_time', models.DateTimeField()),
                ('requested_end_time', models.DateTimeField()),
                ('description', models.TextField(help_text='Why you need this specific time/date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('signed_up_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='lessonscheduler.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
