# Generated by Django 4.2.11 on 2026-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0004_alter_lesson_dj_alter_lesson_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classsignup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
