# Generated by Django 6.0.2 on 2026-04-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0004_alter_lesson_dj_alter_lesson_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
