# Generated by Django 4.2.11 on 2026-04-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0005_alter_classrequest_id_alter_classsignup_id_and_more'),
        ('lessonscheduler', '0005_lesson_image'),
    ]

    operations = [
    ]
