# Generated by Django 6.0.1 on 2026-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classsignup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
