# Generated by Django 6.0.2 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0008_alter_lesson_experience_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='experience_requirements',
            field=models.TextField(default='No specific requirements', help_text="e.g., 'Beginner', 'Intermediate', or specific skills needed"),
        ),
    ]
