# Generated by Django 6.0.2 on 2026-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0009_alter_lesson_experience_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='experience_requirements',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced')], max_length=30),
        ),
    ]
