# Generated by Django 6.0.2 on 2026-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0010_alter_lesson_experience_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='requested_equipment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='requested_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='requested_skill_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced')], default='Beginner', max_length=30),
        ),
    ]
