# Generated by Django 6.0.2 on 2026-04-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonscheduler', '0011_classrequest_requested_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_requests', to='lessonscheduler.lesson'),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Class'), ('edit', 'Edit Existing Class')], default='new', max_length=10),
        ),
    ]
