# Generated by Django 4.2.11 on 2026-04-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_content'),
        ('messaging', '0003_alter_message_content_alter_message_id'),
    ]

    operations = [
    ]
