# Generated by Django 6.0.2 on 2026-04-19

import messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=messaging.models._message_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_token', models.CharField(default='', max_length=32)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
